# Generated by Django 3.0.5 on 2020-04-26 19:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200426_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
