# Generated by Django 3.0.5 on 2020-05-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_banner_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_call_to_action',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
    ]
