# Generated by Django 3.0.5 on 2020-05-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionspage',
            options={'verbose_name': 'Institution Page', 'verbose_name_plural': 'Institution Pages'},
        ),
        migrations.RemoveField(
            model_name='institutionspage',
            name='banner_call_to_action',
        ),
    ]
