# Generated by Django 3.0.5 on 2020-05-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_instituionlistingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituionlistingpage',
            name='custom_title',
            field=models.CharField(help_text='Title overwrite', max_length=100),
        ),
    ]
