# Generated by Django 3.0.5 on 2020-05-19 02:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailimages', '0022_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('institutions', '0004_auto_20200519_0223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstituionListingPage',
            new_name='InstitutionListingPage',
        ),
        migrations.RenameModel(
            old_name='InstitutionsPage',
            new_name='InstitutionPage',
        ),
    ]
