# Generated by Django 3.0.5 on 2020-05-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_institutionlistingpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionpage',
            name='sat_scores_average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
