# Generated by Django 3.0.5 on 2020-05-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_institutionimagegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionpage',
            name='dapip_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionpage',
            name='ope_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
