# Generated by Django 3.0.5 on 2020-05-16 23:53

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_rootpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add text', required=True)), ('classes', wagtail.core.blocks.CharBlock(help_text='Comma delitimed class names', required=False))]))], blank=True, null=True),
        ),
    ]
