# Generated by Django 3.0.5 on 2020-05-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200521_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecareerhistory',
            name='year_departed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecareerhistory',
            name='year_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
